[tool.poetry]
name = "teamline"
version = "0.1.0"
description = ""
authors = ["Guido Rainuzzo <hi@guido.nyc>"]

[tool.poetry.dependencies]
python = "^3.7.3"
arrow = "^0.15.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
